---
title: "R Notebook"
output: html_notebook
---

This is how I'm changing the R murder data so that they don't have to deal as much with factors and characters, as well as 
trying to make it a little easier on the eyes. 

```{r}
library(tidyverse)

#load ("murder_data.Rda")
load (url("https://cronkitedata.github.io/cronkite-docs/r-stats/murder_data.Rda"))

#print out the structure of the dataset
str(murder_data)

```

```{r}

new_murder_data <- 
  murder_data %>%
  mutate (
    id = ID,
    county_code = CNTYFIPS, 
    ori_code = Ori,
    state_name = State,
    agency_name = Agency,
    solved = Solved,
    year = Year,
    month = Month, 
    situation_code = as.integer(Situation),
    situation = as.character(Situation),
    victim_age = VicAge,
    victim_sex = VicSex,
    victim_race = VicRace,
    victim_hisp = VicEthnic,
    offend_age = OffAge,
    offend_sex = OffSex,
    offend_race = OffRace,
    offend_hisp = OffEthnic,
    weapon_code = as.integer(Weapon),
    weapon = as.character(Weapon),
    relationship_code = as.integer(Relationship),
    relationship = as.character(Relationship),
    circumstance_code = as.integer(Circumstance),
    circumstance = as.character(Circumstance)
  ) %>%
  select (id:circumstance)


```

now the new murder data has codes and words for the ones that have a lot of factors. 


```{r}

distinct (new_murder_data , weapon_code, weapon) %>% arrange (weapon_code)


new_murder_data %>%
  mutate (is_gun = if_else (weapon_code %in% c(1,2,3,4,5), "Yes", "No" )) %>%
  select (weapon, weapon_code, is_gun)

```

now we have codes and 