remote_theme: pmarsceill/just-the-docs
#theme:        "just-the-docs"
base_url:    "/cronkite-docs/"
url:         "https://cronkitedata.github.io"


defaults:
 - scope:
     path:    ""
   values:
     layout:  "home"

exclude: ["node_modules/",
          "*.gemspec",
          "*.gem",
          "Gemfile",
          "Gemfile.lock",
          "package.json",
          "script/",
          "LICENSE.txt",
          "lib/",
          "bin/",
          "README.md",
          "Rakefile",
          "*.DS_Store",
          ]

aux_links:
  "Sarah Cohen / Knight Chair / Cronkite School":
    - "https://isearch.asu.edu/profile/3189494"

# Enable or disable the site search
#search_enabled: false

title: Data reporting @ Cronkite
description: A collection of materials used in the data reporting class at ASU's Cronkite School of Journalism
